# Тестовые данные
GET http://localhost:3123/api HTTP/1.1

###

# Фильмы
## Получить список фильмов

GET http://localhost:5000/movies?limit=3&genre=Romance HTTP/1.1
Content-Type: application/json

###

## Создать карточку фильма

POST http://localhost:5000/movies HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1pc3RlcnR3aXN0ZXJAZ21haWwuY29tIiwiaWQiOiI2M2RlMWMwYzkwMTExZWNiYjE3ZmQ5MzYiLCJpYXQiOjE2NzU1MDA1NjUsImV4cCI6MTY3NTY3MzM2NX0.JYT_0Qvqj8q0ayAujsRUjIuZ6bMxkEqHTrGq9m4p-z0

{
  "title": "The Hateful Eight-2",
  "description": "In the dead of a Wyoming winter, a bounty hunter and his prisoner find shelter in a cabin currently inhabited by a collection of nefarious characters.",
  "postDate": "2023-01-25T21:00:00.000Z",
  "genre": "Crime",
  "year": 2015,
  "preview": "https://www.imdb.com/video/vi2079306521/?playlistId=tt3460252&ref_=tt_ov_vi",
  "video": "https://www.imdb.com/video/vi2079306521/?playlistId=tt3460252&ref_=tt_ov_vi",
  "actors": [
    "Samuel L. Jackson", 
    "Kurt Russell", 
    "Jennifer Jason Leigh"
    ],
  "director": "Quentin Tarantino",
  "duration": 168,
  "poster": "https://www.imdb.com/title/tt3460252/mediaviewer/rm2736055040/?ref_=tt_ov_i",
  "backgroundImage": "https://compote.slate.com/images/cdcf74ae-c30a-483a-b99c-7e888c4bf1f4.jpg",
  "backgroundColor": "#000000"
}

###

## Получить информацию по фильму

GET http://localhost:5000/movies/63c29007cdb71a70b34f9f33 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1pc3RlcnR3aXN0ZXJAZ21haWwuY29tIiwiaWQiOiI2M2RlMWMwYzkwMTExZWNiYjE3ZmQ5MzYiLCJpYXQiOjE2NzU2OTc3NDIsImV4cCI6MTY3NTg3MDU0Mn0.K3nlwAXalulrR48eLPvAp1jJU4iR5BCeOpbT3aqm34c

###

## Редактировать информацию по фильму

PATCH  http://localhost:5000/movies/63c29007cdb71a70b34f9f44 HTTP/1.1
Content-Type: application/json

{
  "genre": "Comedy"
}

###

## Удалить фильм

DELETE http://localhost:5000/movies/63d2b350ed9d204b6baa88c2 HTTP/1.1

###

## Получить промо фильм

GET http://localhost:5000/movies/promo HTTP/1.1
Content-Type: application/json

###

## Получить комментарии к фильму

GET http://localhost:5000/movies/63c29007cdb71a70b34f9f2b/comments HTTP/1.1
Content-Type: application/json

###

## Создать комментарий к фильму
POST http://localhost:5000/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1pc3RlcnR3aXN0ZXJAZ21haWwuY29tIiwiaWQiOiI2M2RlMWMwYzkwMTExZWNiYjE3ZmQ5MzYiLCJpYXQiOjE2NzU1MDA1NjUsImV4cCI6MTY3NTY3MzM2NX0.JYT_0Qvqj8q0ayAujsRUjIuZ6bMxkEqHTrGq9m4p-z0

{
  "rating": 9,
  "text": "Восхитетльно, невероятно, мой словарный запас слишком мал",
  "movieId": "63c29007cdb71a70b34f9f2b"
}

###

# Пользователи
## Регистрация пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Twister",
  "email": "mistertwister@gmail.com",
  "avatar": "twister.png",
  "password": "353twists"
}

###

## Авторизация пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "mistertwister@gmail.com",
  "password": "353twists"
}

###

## Проверка токена пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1pc3RlcnR3aXN0ZXJAZ21haWwuY29tIiwiaWQiOiI2M2RlMWMwYzkwMTExZWNiYjE3ZmQ5MzYiLCJpYXQiOjE2NzU1MDA1NjUsImV4cCI6MTY3NTY3MzM2NX0.JYT_0Qvqj8q0ayAujsRUjIuZ6bMxkEqHTrGq9m4p-z0

###

## Получить список "к просмотру"

GET http://localhost:5000/users/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1pc3RlcnR3aXN0ZXJAZ21haWwuY29tIiwiaWQiOiI2M2RlMWMwYzkwMTExZWNiYjE3ZmQ5MzYiLCJpYXQiOjE2NzU2OTc3NDIsImV4cCI6MTY3NTg3MDU0Mn0.K3nlwAXalulrR48eLPvAp1jJU4iR5BCeOpbT3aqm34c

###

## Изменить статус фильма в списке "к просмотру"

POST http://localhost:5000/users/favorites/63c29007cdb71a70b34f9f33/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Im1pc3RlcnR3aXN0ZXJAZ21haWwuY29tIiwiaWQiOiI2M2RlMWMwYzkwMTExZWNiYjE3ZmQ5MzYiLCJpYXQiOjE2NzU2OTc3NDIsImV4cCI6MTY3NTg3MDU0Mn0.K3nlwAXalulrR48eLPvAp1jJU4iR5BCeOpbT3aqm34c

###

## Отправка аватарки пользователю

POST http://localhost:5000/users/63c29007cdb71a70b34f9f2e/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< Users/adm/Downloads/images/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###